import pytest
from fastapi.testclient import TestClient

from backend.app.core.database import SessionLocal
from backend.app.main import app as backend_app
from backend.app.models.raw import ProviderEvent
from simulator.main import state, tick_simulation

backend_client = TestClient(backend_app)

@pytest.fixture(autouse=True)
def clean_events():
    """Clean database raw events table before and after each test."""
    db = SessionLocal()
    try:
        db.query(ProviderEvent).delete()
        db.commit()
    finally:
        db.close()
    yield
    db = SessionLocal()
    try:
        db.query(ProviderEvent).delete()
        db.commit()
    finally:
        db.close()


def test_simulator_to_ingestion_integration(monkeypatch):
    """Verify that events generated by the simulator can be ingested by the backend API."""
    
    # Mock requests.post in simulator/main.py to call our TestClient directly
    def mock_post(url, json=None, **kwargs):
        endpoint = "/api/v1/events"
        if "batch" in url:
            endpoint = "/api/v1/events/batch"
            
        # Call TestClient instead of requests
        response = backend_client.post(endpoint, json=json)
        
        # Mock Response object
        class MockResponse:
            status_code = response.status_code
            text = response.text
        return MockResponse()
        
    monkeypatch.setattr("requests.post", mock_post)
    
    # Set simulator scenario to NORMAL
    state.current_scenario = "NORMAL"
    
    # 1. Trigger single tick simulation
    events = tick_simulation()
    assert len(events) >= 0  # might be 0 due to randomness, but usually generates some events
    
    # Force generate events by running multiple ticks until we get some events
    events = []
    for _ in range(20):
        events.extend(tick_simulation())
        if len(events) > 0:
            break
            
    assert len(events) > 0, "Simulator did not generate any events in 20 ticks"
    
    # 2. Ingest the events manually via the mocked post
    from simulator.main import send_events_to_backend
    send_events_to_backend(events)
    
    # 3. Verify they exist in PostgreSQL raw events table
    db = SessionLocal()
    try:
        db_events = db.query(ProviderEvent).all()
        assert len(db_events) > 0
        
        # Verify the structure in database matches what simulator sent
        for db_event in db_events:
            assert db_event.provider == "simulator"
            assert db_event.processing_status == "PENDING"
            assert "organization_external_id" in db_event.payload
            assert db_event.payload_hash is not None
    finally:
        db.close()
