import logging
from typing import Any

from backend.app.models.core import (
    Build,
    Change,
    Deployment,
    Incident,
    Review,
    WorkItem,
)
from backend.app.models.raw import ProviderEvent
from backend.app.normalization.base import BaseNormalizer

logger = logging.getLogger("codesense.normalization.simulator")

class SimulatorNormalizer(BaseNormalizer):
    """Normalizes events generated by the CodeSense simulator."""
    
    def normalize(self, raw_event: ProviderEvent) -> None:
        payload: dict[str, Any] = raw_event.payload
        occurred_at = raw_event.event_timestamp or raw_event.received_at
        
        # 1. Resolve / Create base topology entities
        org_ext_id = payload.get("organization_external_id", "sim-org-default")
        org_name = payload.get("organization_name", "Simulator Org")
        org = self.get_or_create_organization(org_ext_id, org_name)
        
        team_ext_id = payload.get("team_external_id", "sim-team-default")
        team_name = payload.get("team_name", "Simulator Team")
        team = self.get_or_create_team(org.id, team_ext_id, team_name)
        
        proj_ext_id = payload.get("project_external_id", "sim-proj-default")
        proj_name = payload.get("project_name", "Simulator Project")
        project = self.get_or_create_project(org.id, team.id, proj_ext_id, proj_name)
        
        repo_ext_id = payload.get("repository_external_id", "sim-repo-default")
        repo_name = payload.get("repository_name", "Simulator Repo")
        repo = self.get_or_create_repository(team.id, project.id, "simulator", repo_ext_id, repo_name)
        
        event_type = raw_event.event_type
        
        # Determine internal entity mapping based on event type
        entity_type: str | None = None
        entity_id: Any | None = None
        
        # 2. Map and upsert specific core entities
        # A. WORK ITEMS
        if event_type in ("WORK_ITEM_CREATED", "WORK_ITEM_STARTED", "WORK_ITEM_COMPLETED"):
            wi_id = payload.get("work_item_id")
            if wi_id:
                wi = self.db.query(WorkItem).filter_by(provider="simulator", external_id=wi_id).first()
                if not wi:
                    wi = WorkItem(
                        team_id=team.id,
                        project_id=project.id,
                        repository_id=repo.id,
                        provider="simulator",
                        external_id=wi_id,
                        item_type=payload.get("item_type", "TASK"),
                        title=payload.get("title", f"Work Item {wi_id}"),
                        status=payload.get("status", "BACKLOG"),
                        priority=payload.get("priority", "MEDIUM")
                    )
                    self.db.add(wi)
                else:
                    if "status" in payload:
                        wi.status = payload["status"]
                        if payload["status"] == "IN_PROGRESS" and not wi.started_at:
                            wi.started_at = occurred_at
                        elif payload["status"] == "COMPLETED" and not wi.completed_at:
                            wi.completed_at = occurred_at
                            
                self.db.flush()
                entity_type = "work_item"
                entity_id = wi.id

        # B. CHANGES (PR/MR)
        elif event_type in ("CHANGE_CREATED", "CHANGE_MERGED", "CHANGE_CLOSED"):
            change_id = payload.get("change_id")
            if change_id:
                ch = self.db.query(Change).filter_by(provider="simulator", external_id=change_id).first()
                if not ch:
                    wi_id = payload.get("work_item_id")
                    wi = self.db.query(WorkItem).filter_by(provider="simulator", external_id=wi_id).first() if wi_id else None
                    ch = Change(
                        team_id=team.id,
                        repository_id=repo.id,
                        work_item_id=wi.id if wi else None,
                        provider="simulator",
                        external_id=change_id,
                        title=payload.get("title", f"Change {change_id}"),
                        status=payload.get("status", "OPEN"),
                        created_at=occurred_at,
                        additions=payload.get("additions", 0),
                        deletions=payload.get("deletions", 0),
                        changed_files=payload.get("changed_files", 0)
                    )
                    self.db.add(ch)
                else:
                    if "status" in payload:
                        ch.status = payload["status"]
                        if payload["status"] == "MERGED":
                            ch.merged_at = occurred_at
                        elif payload["status"] == "CLOSED":
                            ch.closed_at = occurred_at
                            
                self.db.flush()
                entity_type = "change"
                entity_id = ch.id

        # C. REVIEWS
        elif event_type in ("REVIEW_REQUESTED", "REVIEW_COMPLETED"):
            rev_id = payload.get("review_id")
            change_ext_id = payload.get("change_id")
            
            # Resolve change reference
            ch = self.db.query(Change).filter_by(provider="simulator", external_id=change_ext_id).first() if change_ext_id else None
            
            if rev_id and ch:
                rev = self.db.query(Review).filter_by(provider="simulator", external_id=rev_id).first()
                if not rev:
                    rev = Review(
                        change_id=ch.id,
                        provider="simulator",
                        external_id=rev_id,
                        reviewer_reference=payload.get("reviewer_reference"),
                        status=payload.get("status", "PENDING"),
                        requested_at=occurred_at
                    )
                    self.db.add(rev)
                else:
                    if "status" in payload:
                        rev.status = payload["status"]
                        if payload["status"] == "APPROVED":
                            rev.completed_at = occurred_at
                            
                self.db.flush()
                entity_type = "review"
                entity_id = rev.id

        # D. BUILDS
        elif event_type in ("BUILD_STARTED", "BUILD_COMPLETED", "BUILD_SUCCEEDED", "BUILD_FAILED"):
            build_id = payload.get("build_id")
            change_ext_id = payload.get("change_id")
            ch = self.db.query(Change).filter_by(provider="simulator", external_id=change_ext_id).first() if change_ext_id else None
            
            if build_id:
                b = self.db.query(Build).filter_by(provider="simulator", external_id=build_id).first()
                if not b:
                    b = Build(
                        team_id=team.id,
                        repository_id=repo.id,
                        change_id=ch.id if ch else None,
                        provider="simulator",
                        external_id=build_id,
                        status=payload.get("status", "RUNNING"),
                        branch=payload.get("branch", "main"),
                        commit_sha=payload.get("commit_sha"),
                        started_at=occurred_at
                    )
                    self.db.add(b)
                else:
                    if "status" in payload:
                        b.status = payload["status"]
                        if payload["status"] in ("SUCCESS", "FAILED", "CANCELLED"):
                            b.completed_at = occurred_at
                            b.duration_seconds = payload.get("duration_seconds")
                            
                self.db.flush()
                entity_type = "build"
                entity_id = b.id

        # E. DEPLOYMENTS
        elif event_type in ("DEPLOYMENT_STARTED", "DEPLOYMENT_COMPLETED", "DEPLOYMENT_FAILED", "DEPLOYMENT_ROLLED_BACK"):
            dep_id = payload.get("deployment_id")
            change_ext_id = payload.get("change_id")
            ch = self.db.query(Change).filter_by(provider="simulator", external_id=change_ext_id).first() if change_ext_id else None
            
            if dep_id:
                d = self.db.query(Deployment).filter_by(provider="simulator", external_id=dep_id).first()
                if not d:
                    d = Deployment(
                        team_id=team.id,
                        repository_id=repo.id,
                        change_id=ch.id if ch else None,
                        provider="simulator",
                        external_id=dep_id,
                        environment=payload.get("environment", "PRODUCTION"),
                        status=payload.get("status", "RUNNING"),
                        version=payload.get("version"),
                        started_at=occurred_at
                    )
                    self.db.add(d)
                else:
                    if "status" in payload:
                        d.status = payload["status"]
                        if payload["status"] in ("SUCCESS", "FAILED", "ROLLED_BACK", "CANCELLED"):
                            d.completed_at = occurred_at
                            d.duration_seconds = payload.get("duration_seconds")
                            
                self.db.flush()
                entity_type = "deployment"
                entity_id = d.id

        # F. INCIDENTS
        elif event_type in ("INCIDENT_CREATED", "INCIDENT_ACKNOWLEDGED", "INCIDENT_RESOLVED"):
            inc_id = payload.get("incident_id")
            if inc_id:
                inc = self.db.query(Incident).filter_by(provider="simulator", external_id=inc_id).first()
                if not inc:
                    inc = Incident(
                        team_id=team.id,
                        repository_id=repo.id,
                        provider="simulator",
                        external_id=inc_id,
                        title=payload.get("title", f"Incident {inc_id}"),
                        severity=payload.get("severity", "SEV3"),
                        status=payload.get("status", "OPEN"),
                        created_at=occurred_at
                    )
                    self.db.add(inc)
                else:
                    if "status" in payload:
                        inc.status = payload["status"]
                        if payload["status"] == "ACKNOWLEDGED":
                            inc.acknowledged_at = occurred_at
                        elif payload["status"] == "RESOLVED":
                            inc.resolved_at = occurred_at
                            
                self.db.flush()
                entity_type = "incident"
                entity_id = inc.id

        # 3. Write Canonical Event
        self.create_canonical_event(
            raw_event=raw_event,
            org_id=org.id,
            team_id=team.id,
            project_id=project.id,
            repo_id=repo.id,
            event_type=event_type,
            occurred_at=occurred_at,
            actor_ref=payload.get("actor_ref"),
            entity_type=entity_type,
            entity_id=entity_id,
            metadata=payload
        )
